WebApplication5/WebApplication5/Models/Question.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public int Mark { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Category Category { get; set; }
    }
}

WebApplication5/WebApplication5/Controllers/AnswersController.cs
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApplication5.Filters;
using WebApplication5.Models;
namespace WebApplication5.Controllers
{
    [AdminAuthorizeAttribute]
    public class AnswersController : Controller
    {
        private OnlineAptitudeTestEntities db = new OnlineAptitudeTestEntities();

        // GET: Answers
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page,int? QuestionId)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CorrectChoiceSortParm = sortOrder == "CorrectChoice" ? "correctchoice_desc" : "CorrectChoice";
            ViewBag.QuestionNameSortParm = sortOrder == "QuestionName" ? "questionname_desc" : "QuestionName";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var answers = from a in db.Answers select a;
            if (!String.IsNullOrEmpty(searchString))
            {
                answers = answers.Where(a => a.Name.ToUpper().Contains(searchString.ToUpper()) || a.Question.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            if (QuestionId != null)
            {
                answers = answers.Where(a => a.QuestionId == QuestionId);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    answers = answers.OrderByDescending(q => q.Name);
                    break;
                case "CorrectChoice":
                    answers = answers.OrderBy(q => q.IsRightAnswer);
                    break;
                case "correctchoice_desc":
                    answers = answers.OrderByDescending(q => q.IsRightAnswer);
                    break;
                case "questionname_desc":
                    answers = answers.OrderBy(q => q.Question.Name);
                    break;
                case "QuestionName":
                    answers = answers.OrderByDescending(q => q.Question.Name);
                    break;
                default:
                    answers = answers.OrderBy(q => q.Name);
                    break;
            }
            var items = answers.ToPagedList(page ?? 1, 10);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_AnswerPartial", items);
            }
            return View(items);
        }

        // GET: Answers/Create
        public ActionResult Create()
        {
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name");
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,QuestionId,IsRightAnswer")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name", answer.QuestionId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,QuestionId,IsRightAnswer")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Answer answer = await db.Answers.FindAsync(id);
            db.Answers.Remove(answer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult AutoComplete(string term)
        {
            var answers = db.Answers.Where(a => a.Name.ToUpper().Contains(term.ToUpper()) || a.Question.Name.ToUpper().Contains(term.ToUpper())).Select(a => a.Name);
            return Json(answers, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication5/WebApplication5/Controllers/QuestionsController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApplication5.Filters;
using WebApplication5.Models;
namespace WebApplication5.Controllers
{
    [AdminAuthorizeAttribute]
    public class QuestionsController : Controller
    {
        private OnlineAptitudeTestEntities db = new OnlineAptitudeTestEntities();

        // GET: Questions
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, int? Mark, int? CategoryId, string AdvancedSearchString, DateTime? DateCreated)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.MarkSortParm = sortOrder == "Mark" ? "mark_desc" : "Mark";
            ViewBag.CategorySortParm = sortOrder == "Category" ? "category_desc" : "Category";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var questions = from q in db.Questions select q;
            if (!String.IsNullOrEmpty(AdvancedSearchString))
            {
                questions = questions.Where(q => q.Name.ToUpper().Contains(AdvancedSearchString.ToUpper()));
            }
            else
            {
                if (!String.IsNullOrEmpty(searchString))
                {
                    questions = questions.Where(q => q.Name.ToUpper().Contains(searchString.ToUpper()) || q.Category.Name.ToUpper().Contains(searchString.ToUpper()));
                }
            }
            if (CategoryId != null)
            {
                questions = questions.Where(q => q.CategoryId == CategoryId);
            }
            if (Mark != null)
            {
                questions = questions.Where(q => q.Mark == Mark);
            }
            if (DateCreated != null)
            {
                DateTime dt = (DateTime)DateCreated;
                questions = questions.Where(q => q.DateCreated.Year == dt.Year && q.DateCreated.Month == dt.Month && q.DateCreated.Day == dt.Day);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    questions = questions.OrderByDescending(q => q.Name);
                    break;
                case "Mark":
                    questions = questions.OrderBy(q => q.Mark);
                    break;
                case "mark_desc":
                    questions = questions.OrderByDescending(q => q.Mark);
                    break;
                case "category_desc":
                    questions = questions.OrderByDescending(q => q.Category.Name);
                    break;
                case "Category":
                    questions = questions.OrderBy(q => q.Category.Name);
                    break;
                default:
                    questions = questions.OrderBy(q => q.Name);
                    break;
            }
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var items = questions.ToPagedList(pageNumber, pageSize);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_QuestionPartial", items);
            }
            return View(items);
        }

        // GET: Questions/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = await db.Questions.FindAsync(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // GET: Questions/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        // POST: Questions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,CategoryId,Mark,Answers,DateCreated")] Question question)
        {
            if (ModelState.IsValid)
            {
                var list = new List<Answer>(question.Answers);
                list.RemoveAll(ans => String.IsNullOrEmpty(ans.Name));
                question.Answers = list;
                db.Questions.Add(question);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", question.CategoryId);
            return View(question);
        }

        // GET: Questions/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = await db.Questions.FindAsync(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", question.CategoryId);
            return View(question);
        }

        // POST: Questions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,CategoryId,Mark")] Question question)
        {
            if (ModelState.IsValid)
            {
                db.Entry(question).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", question.CategoryId);
            return View(question);
        }

        // GET: Questions/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = await db.Questions.FindAsync(id);
            if (question == null)
            {
                return HttpNotFound();
            }
            return View(question);
        }

        // POST: Questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Question question = await db.Questions.FindAsync(id);
            foreach (var item in question.Answers)
            {
                db.Answers.Remove(item);
                await db.SaveChangesAsync();
            }
            db.Questions.Remove(question);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult AutoComplete(string term)
        {
            var questions = db.Questions.Where(q => q.Name.ToUpper().Contains(term.ToUpper()) || q.Category.Name.ToUpper().Contains(term.ToUpper()) || q.Mark.ToString().Contains(term)).Select(q => q.Name);
            return Json(questions, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication5/WebApplication5/Views/Questions/Create.cshtml
@model WebApplication5.Models.Question

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    int i = 0;
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Questions", FormMethod.Post, new { data_abide = "" }))
{
    <div class="row">
        <div class="large-12 columns">
            @Html.AntiForgeryToken()
            <h4>Question</h4>
        </div>
    </div>
    <fieldset>
        <legend>Detail</legend>
        <div class="row">
            <div class="large-12 columns">
                <label>Question:</label>
            </div>
            <div class="large-12 columns">
                @Html.TextAreaFor(model => model.Name, new { rows = "5", required = "" })
                <small class="error">Name is required and must be a string</small>
            </div>
        </div>
        <div class="row">
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-12 columns">
                        <label>Category:</label>
                    </div>
                    <div class="large-12 columns">
                        @Html.DropDownList("CategoryId")
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-12 columns">
                        <label>Mark:</label>
                    </div>
                    <div class="large-12 columns">
                        <select id="Mark" name="Mark">
                            <option value="1">1</option>
                            <option value="2">2</option>
                            <option value="3">3</option>
                            <option value="4">4</option>
                            <option value="5">5</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
    <fieldset>
        <legend>Answers</legend>
        <div class="row">
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-1 columns">
                        <input type="checkbox" value="true" id="Answers[0].IsRightAnswer" name="Answers[0].IsRightAnswer" />
                        <input type="hidden" value="false" name="Answers[0].IsRightAnswer">
                    </div>
                    <div class="large-11 columns">
                        <input type="text" id="Answers[0].Name" name="Answers[0].Name" />
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-1 columns">
                        <input type="checkbox" id="Answers[1].IsRightAnswer" name="Answers[1].IsRightAnswer" value="true" class="has-tip" title="Check if it is the correct answer" data-tooltip data-options="disable_for_touch:true" />
                        <input type="hidden" value="false" name="Answers[1].IsRightAnswer">
                    </div>
                    <div class="large-11 columns">
                        <input type="text" id="Answers[1].Name" name="Answers[1].Name" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-1 columns">
                        <input type="checkbox" value="true" id="Answers[2].IsRightAnswer" name="Answers[2].IsRightAnswer" />
                        <input type="hidden" value="false" name="Answers[2].IsRightAnswer" />
                    </div>
                    <div class="large-11 columns">
                        <input type="text" id="Answers[2].Name" name="Answers[2].Name" />
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-1 columns">
                        <input type="checkbox" id="Answers[3].IsRightAnswer" name="Answers[3].IsRightAnswer" value="true" />
                        <input type="hidden" value="false" name="Answers[3].IsRightAnswer">
                    </div>
                    <div class="large-11 columns">
                        <input type="text" id="Answers[3].Name" name="Answers[3].Name" />
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-1 columns">
                        <input type="checkbox" value="true" id="Answers[4].IsRightAnswer" name="Answers[4].IsRightAnswer" />
                        <input type="hidden" value="false" name="Answers[4].IsRightAnswer">
                    </div>
                    <div class="large-11 columns">
                        <input type="text" id="Answers[4].Name" name="Answers[4].Name" />
                    </div>
                </div>
            </div>
            <div class="large-6 columns">
                <div class="row">
                    <div class="large-1 columns">
                        <input type="checkbox" id="Answers[5].IsRightAnswer" name="Answers[5].IsRightAnswer" value="true" />
                        <input type="hidden" value="false" name="Answers[5].IsRightAnswer">
                    </div>
                    <div class="large-11 columns">
                        <input type="text" id="Answers[5].Name" name="Answers[5].Name" />
                    </div>
                </div>
            </div>
        </div>
    </fieldset>
    <input type="hidden" value="@DateTime.Now" id="DateCreated" name="DateCreated" />
    <div class="row">
        <div class="large-6 columns">
            <a href="/Questions" class="small button">Back to List</a>
        </div>
        <div class="large-6 columns">
            <input type="submit" value="Create" class="small button right" /><br />
        </div>
    </div>
}
@section Validation{
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
}

WebApplication5/WebApplication5/Views/Questions/Delete.cshtml
@model WebApplication5.Models.Question

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this question?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Content
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            Mark
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mark)
        </dd>

        <dt>
            Category Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            Delete this question will also delete @Model.Answers.ToList().Count followwing answers:
        </dt>
        @foreach (var item in Model.Answers)
        {
            <dd>
                @item.Name
            </dd>
        }

    </dl>



    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="small button" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebApplication5/WebApplication5/Views/Questions/Details.cshtml
@model WebApplication5.Models.Question

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@helper Selected(bool value)
{
    if (value)
    {
        @:checked="checked"
    }
}
<h2>Details</h2>

<div>
    <h4>Question</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Mark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Mark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Category.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>
        <dt>
            @Model.Answers.ToList().Count answers:
        </dt>
        @foreach (var item in Model.Answers)
        {
            <dd>
                <input type="checkbox" disabled="disabled" name="@item.Id" id="@item.Id" @Selected(@item.IsRightAnswer) /><label for="@item.Id">@item.Name</label>
            </dd>
        }

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebApplication5/WebApplication5/Views/Questions/Edit.cshtml
@model WebApplication5.Models.Question

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@helper selected(int n, int m)
{
    if (n == m)
    {
        @:selected="selected"
    }
}
<h2>Edit</h2>
@using (Html.BeginForm("Edit", "Questions", FormMethod.Post, new { data_abide = "" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="large-12 columns">
            <label>Question Name:</label>
            @Html.TextAreaFor(m => m.Name, new { rows = "5", required = "" })
            <small class="error">Question content is required</small>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <label>Category:</label>
            @Html.DropDownList("CategoryId")
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <label>Mark:</label>
            <select id="Mark" name="Mark">
                @for (int i = 1; i < 6; i++)
                {
                    <option value="@i" @selected(i, Model.Mark)>@i</option>
                }
            </select>
        </div>
    </div>
    <div class="row">
        <div class="large-6 columns">
            @Html.ActionLink("Back to List", "Index")
        </div>
        <div class="large-6 columns">
            @Html.ActionLink("Edit the answers of this question", "Index", "Answers", new { QuestionId = @Model.Id }, new { @class = "right" })
        </div>
    </div>
    <br />
    <div class="row">
        <div class="large-12 columns">
            <input type="submit" value="Save" class="small button right" />
        </div>
    </div>
}

WebApplication5/WebApplication5/Views/Questions/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<WebApplication5.Models.Question>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
}
@section ResponsiveTable{
    <link href="~/Content/responsive-tables.css" rel="stylesheet" />
}
@section Paging{
    <link href="~/Content/PagedList.css" rel="stylesheet" />
}
<h3>Question Management</h3>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<ul class="tabs" data-tab>
    <li class="tab-title active"><a href="#panel2-1">Basic Search</a></li>
    <li class="tab-title"><a href="#panel2-2">Advanced Search</a></li>
</ul>
<div class="tabs-content">
    <div class="content active" id="panel2-1">
        <div class="content active" id="panel2-1">
            @using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "Sample", HttpMethod = "GET", InsertionMode = InsertionMode.Replace }))
            {
                <div class="row">
                    <div class="large-5 columns">
                        @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new { @placeholder = "Enter your search here", id = "SearchString" })
                    </div>
                    <div class="large-2 columns">
                        <input type="submit" value="Search" class="small button postfix " />
                    </div>
                    <div class="large-5 columns"></div>
                </div>
            }
        </div>

    </div>
    <div class="content" id="panel2-2">
        @using (Ajax.BeginForm(new AjaxOptions { UpdateTargetId = "Sample", HttpMethod = "GET", InsertionMode = InsertionMode.Replace }))
        {
            <div class="row">
                <div class="large-3 columns">
                    <label>Question Name:</label>
                    @Html.TextBox("AdvancedSearchString", ViewBag.CurrentFilter as string, new { @placeholder = "Enter your search here", id = "AdvancedSearchString" })
                </div>
                <div class="large-3 columns">
                    <label>Question Type:</label>
                    <select id="CategoryId" name="CategoryId">
                        <option value="null">---All---</option>
                        <option value="1">General Knowledge</option>
                        <option value="2">Mathematics</option>
                        <option value="3">Computer Technology</option>
                    </select>
                </div>
                <div class="large-3 columns">
                    <label>Mark:</label>
                    <select id="Mark" name="Mark">
                        <option value="null">---All---</option>
                        <option value="1">1</option>
                        <option value="2">2</option>
                        <option value="3">3</option>
                        <option value="4">4</option>
                        <option value="5">5</option>
                    </select>
                </div>
                <div class="large-3 columns">
                    <label>Date Created:</label>
                    <input type="datetime" id="DateCreated" name="DateCreated" value="" readonly="readonly" />
                </div>
            </div>
            <div class="row">
                <div class="large-12 columns">
                    <input type="submit" class="small button right" value="Search" />
                </div>
            </div>
        }
    </div>
</div>
@Html.Partial("_QuestionPartial", Model)
@section ResponsiveTableJs{
    <script src="~/Scripts/responsive-tables.js"></script>
}
@section Ajax{
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
}
@section AutoCompleteJs{
    <script src="~/Scripts/jquery-ui-1.10.4.custom.min.js"></script>
}
@section AutoCompleteCss{
    <link href="~/Content/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
}
@section AutoScript{
    <script>
        $(function () {
            $("#SearchString").autocomplete({
                source: '@Url.Action("AutoComplete")'
            });
        });
    </script>
}
@section DatePicker{
    <script>
        $(function () {
            $("#DateCreated").datepicker({
                changeYear: true,
                showAnim: "slideDown",
                maxDate: new Date()
            });
        });
    </script>
}