WebApplication5/WebApplication5/Models/StatisticsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication5.Models
{
    public class StatisticsViewModel
    {
        public DateTime FromDate { get; set; }
        public DateTime ToDate { get; set; }
        public string Factor { get; set; }
    }
}

WebApplication5/WebApplication5/Controllers/StatisticsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using WebApplication5.Filters;
using WebApplication5.Helpers;
using WebApplication5.Models;
namespace WebApplication5.Controllers
{
    [AdminAuthorizeAttribute]
    public class StatisticsController : Controller
    {

        private OnlineAptitudeTestEntities db = new OnlineAptitudeTestEntities();
        // GET: Statistics
        public ActionResult Index()
        {
            ViewBag.Factor = "Day";
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(StatisticsViewModel svm)
        {
            ViewBag.FromDate = svm.FromDate.ToShortDateString();
            ViewBag.ToDate = svm.ToDate.ToShortDateString();
            ViewBag.Factor = svm.Factor;
            List<ChartViewModel> list = new List<ChartViewModel>();
            switch (svm.Factor)
            {
                case "Day":
                    for (int i = 0; svm.ToDate.CompareTo(svm.FromDate.AddDays(i)) >= 0; i++)
                    {
                        ChartViewModel cvm = new ChartViewModel();
                        DateTime temp = svm.FromDate.AddDays(i);
                        int year = temp.Year;
                        string month = temp.Month < 10 ? "0" + temp.Month.ToString() : temp.Month.ToString();
                        string day = temp.Day < 10 ? "0" + temp.Day.ToString() : temp.Day.ToString();
                        cvm.Time = "" + year + "-" + month + "-" + day;
                        DateTime newDate = svm.FromDate.AddDays(i);
                        var total = from can in db.Candidates where can.DateTaken.HasValue && can.DateTaken.Value.Day == newDate.Day && can.DateTaken.Value.Month == newDate.Month && can.DateTaken.Value.Year == newDate.Year select can;
                        var passed = total.Where(can => can.Passed);
                        cvm.Passed = passed.ToList().Count();
                        cvm.Total = total.ToList().Count();
                        list.Add(cvm);
                    }
                    break;
                case "Week":
                    Calendar calendar = CultureInfo.InvariantCulture.Calendar;
                    for (int i = 0; calendar.GetWeekOfYear(svm.FromDate.AddDays(i), CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday) <= calendar.GetWeekOfYear(svm.ToDate, CalendarWeekRule.FirstFourDayWeek, DayOfWeek.Monday); i += 7)
                    {
                        ChartViewModel cvm = new ChartViewModel();
                        DateTime startDate = FirstDayOfWeekUtility.GetFirstDayOfWeek(svm.FromDate.AddDays(i));
                        int total = 0;
                        int passed = 0;
                        for (int n = 0; n < 6; n++)
                        {
                            DateTime temp = startDate.AddDays(n);
                            var totalCandidates = (from can in db.Candidates where can.DateTaken.HasValue && can.DateTaken.Value.Day == temp.Day && can.DateTaken.Value.Month == temp.Month && can.DateTaken.Value.Year == temp.Year select can).ToList();
                            var passedCandidates = totalCandidates.Where(can => can.Passed);
                            total += totalCandidates.Count;
                            passed += passedCandidates.ToList().Count;
                        }
                        cvm.Passed = passed;
                        cvm.Total = total;
                        cvm.Time = startDate.ToShortDateString() + "-" + startDate.AddDays(6).ToShortDateString();
                        list.Add(cvm);
                    }
                    break;
                case "Month":
                    for (int i = 0; svm.FromDate.AddMonths(i).Month <= svm.ToDate.Month; i++)
                    {
                        ChartViewModel cvm = new ChartViewModel();
                        int total = 0;
                        int passed = 0;
                        DateTime newFromDate = svm.FromDate.AddMonths(i);
                        for (int n = 0; newFromDate.AddDays(n).Month == newFromDate.Month; n++)
                        {
                            DateTime temp = newFromDate.AddDays(n);
                            var totalCandidates = from can in db.Candidates where can.DateTaken.HasValue && can.DateTaken.Value.Day == temp.Day && can.DateTaken.Value.Month == temp.Month && can.DateTaken.Value.Year == temp.Year select can;
                            var passedCandidates = totalCandidates.Where(can => can.Passed);
                            total += totalCandidates.ToList().Count;
                            passed += passedCandidates.ToList().Count;
                        }
                        cvm.Passed = passed;
                        cvm.Total = total;
                        cvm.Time = CultureInfo.CurrentCulture.DateTimeFormat.GetMonthName(newFromDate.Month);
                        list.Add(cvm);
                    }
                    break;
                default:
                    break;
            }
            return View(list);
        }
    }
}

WebApplication5/WebApplication5/Views/Statistics/Index.cshtml
@using WebApplication5.Models
@model List<WebApplication5.Models.ChartViewModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutPage.cshtml";
    string database = @ViewBag.Data;
}
@helper Selected(string n, string m)
{
    if (n.Equals(m))
    {
        @:checked="checked"
    }
}
@if (Model != null)
{
    @section HighChartJs{
        <script src="http://code.highcharts.com/highcharts.js"></script>
        <script src="http://code.highcharts.com/modules/exporting.js"></script>
        <script src="http://canvg.googlecode.com/svn/trunk/rgbcolor.js"></script>
        <script src="http://canvg.googlecode.com/svn/trunk/canvg.js"></script>
        <script>
            (function (H) {
                H.Chart.prototype.createCanvas = function (divId) {
                    var svg = this.getSVG(),
                        width = parseInt(svg.match(/width="([0-9]+)"/)[1]),
                        height = parseInt(svg.match(/height="([0-9]+)"/)[1]),
                        canvas = document.createElement('canvas');
                    canvas.setAttribute('width', width);
                    canvas.setAttribute('height', height);
                    if (canvas.getContext && canvas.getContext('2d')) {
                        canvg(canvas, svg);
                        var image = canvas.toDataURL("image/png")
                            .replace("image/png", "image/octet-stream");
                        window.location.href = image;
                    } else {
                        alert("Your browser doesn't support this feature, please use a modern browser");
                    }
                }
            }(Highcharts));

            $(function () {
                $('#container').highcharts({
                    chart: {
                        type: 'bar'
                    },
                    title: {
                        text: 'Passed and total candidate comparison'
                    },
                    subtitle: {
                        text: 'From @ViewBag.FromDate to @ViewBag.ToDate'
                    },

                    xAxis: {
                        categories: [
                            @for (int i = 0; i < Model.Count; i++)
                        {
                            @Html.Raw("'"+@Model[i].Time+"'")
                            if (i < Model.Count - 1)
                            {
                                @Html.Raw(",")
                            }
                        }
                        ]
                    },
                    plotOptions: {
                        series: {
                            cursor: 'pointer',
                            point: {
                                events: {
                                    click: function () {
                                        var s=this.category;
                                        window.location.href = '/Candidates/FilterCandidatesByDate?DateTaken='+this.category
                                    }
                                }
                            }
                        }
                    },
                    yAxis: {
                        title: {
                            text: 'Amount of candidates'
                        }
                    },
                    exporting: {
                        buttons: {
                            contextButton: {
                                menuItems: [{
                                    text: 'Print',
                                    onclick: function () {
                                        this.print();
                                    }
                                }, {
                                    text: 'Save as PNG',
                                    onclick: function () {
                                        this.createCanvas();
                                    },
                                    separator: false
                                }]
                            }
                        }
                    },
                    series: [{
                        name: 'Passed Candidates',
                        data: [
                            @for (int i = 0; i < Model.Count; i++)
                        {
                            @Html.Raw(@Model[i].Passed)
                            if (i < Model.Count - 1)
                            {
                                @Html.Raw(",")
                            }
                        }
                        ]
                    }, {
                        name: 'Total Candidates',
                        data: [
                            @for (int i = 0; i < Model.Count; i++)
                                {
                                 @Html.Raw(@Model[i].Total)
                            if (i < Model.Count - 1)
                            {
                                @Html.Raw(",")
                            }
                        }
                        ]
                    }]
                });
            });
        </script>
    }
}
@section AutoCompleteJs{
    <script src="~/Scripts/jquery-ui-1.10.4.custom.min.js"></script>
    <script>
        $(function () {
            $("#FromDate").datepicker({
                changeYear: true,
                showAnim: "slideDown",
                changeMonth: true,
                numberOfMonths: 3,
                maxDate: new Date(),
                showWeek: true,
                firstDay: 1,
                onClose: function (selectedDate) {
                    $("#ToDate").datepicker("option", "minDate", selectedDate);
                }
            });
            $("#ToDate").datepicker({
                changeYear: true,
                showAnim: "slideDown",
                changeMonth: true,
                numberOfMonths: 3,
                maxDate: new Date(),
                showWeek: true,
                firstDay: 1,
                onClose: function (selectedDate) {
                    $("#FromDate").datepicker("option", "maxDate", selectedDate);
                }
            });
        });
    </script>
}

@section AutoCompleteCss{
    <link href="~/Content/jquery-ui-1.10.4.custom.min.css" rel="stylesheet" />
}
<br />
<h3>Statistics</h3>
<hr />
@using (Html.BeginForm("Index", "Statistics", FormMethod.Post, new { data_abide = "" }))
{
    @Html.AntiForgeryToken()
    <div class="row">
        <div class="large-4 columns">
            <label>From Date:</label>
            <input type="text" required pattern="month_day_year" id="FromDate" name="FromDate" value="@ViewBag.FromDate" readonly="readonly" />
            <small class="error">Time is required</small>
        </div>
        <div class="large-4 columns">
            <label>To Date:</label>
            <input type="text" required pattern="month_day_year" id="ToDate" name="ToDate" value="@ViewBag.ToDate" readonly="readonly" />
            <small class="error">Time is required</small>
        </div>
        <div class="large-4 columns">
            <label>Filter by:</label>
            <input type="radio" value="Day" name="Factor" id="FactorDay" @Selected(@ViewBag.Factor, "Day") /><label for="FactorDay">Day</label>
            <input type="radio" value="Week" name="Factor" id="FactorWeek" @Selected(@ViewBag.Factor, "Week") /><label for="FactorWeek">Week</label>
            <input type="radio" value="Month" name="Factor" id="FactorMonth" @Selected(@ViewBag.Factor, "Month") /><label for="FactorMonth">Month</label>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <input type="submit" value="Submit" class="small button right" />
        </div>
    </div>
}
<div id="container"></div>