WebApplication5/WebApplication5/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebApplication5.Models;
using WebApplication5.Helpers;
namespace WebApplication5.Controllers
{
    public class AdminController : Controller
    {
        private OnlineAptitudeTestEntities db = new OnlineAptitudeTestEntities();
        // GET: Admin
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Login(LoginViewModel lvm, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                var manager = await db.Managers.FindAsync(lvm.UserName);
                if (manager != null && PasswordHash.ValidatePassword(lvm.Password, manager.Pass))
                {
                    Session["UserInfo"] = manager;
                    if (lvm.RememberMe)
                    {
                        HttpCookie userNameCookie = new HttpCookie("UserName");
                        HttpCookie passwordCookie = new HttpCookie("Password");
                        userNameCookie.Value = lvm.UserName;
                        passwordCookie.Value = manager.Pass;
                        Response.Cookies.Add(userNameCookie);
                        Response.Cookies.Add(passwordCookie);
                    }
                    if (String.IsNullOrEmpty(returnUrl))
                    {
                        return RedirectToAction("Index", "Questions");
                    }
                    else
                    {
                        return Redirect(returnUrl);
                    }
                }
                else
                {
                    ViewBag.ErrorMsg = "Your user name and password are incorrect";
                }
            }
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }
        public ActionResult Error(int? id)
        {
            ViewBag.ErrorMsg = id == null ? "Unknonwn Error" : "You do not have the right to access this admin page";
            return View();
        }
    }
}

WebApplication5/WebApplication5/Controllers/AnswersController.cs
using PagedList;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApplication5.Filters;
using WebApplication5.Models;
namespace WebApplication5.Controllers
{
    [AdminAuthorizeAttribute]
    public class AnswersController : Controller
    {
        private OnlineAptitudeTestEntities db = new OnlineAptitudeTestEntities();

        // GET: Answers
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page,int? QuestionId)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.CorrectChoiceSortParm = sortOrder == "CorrectChoice" ? "correctchoice_desc" : "CorrectChoice";
            ViewBag.QuestionNameSortParm = sortOrder == "QuestionName" ? "questionname_desc" : "QuestionName";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var answers = from a in db.Answers select a;
            if (!String.IsNullOrEmpty(searchString))
            {
                answers = answers.Where(a => a.Name.ToUpper().Contains(searchString.ToUpper()) || a.Question.Name.ToUpper().Contains(searchString.ToUpper()));
            }
            if (QuestionId != null)
            {
                answers = answers.Where(a => a.QuestionId == QuestionId);
            }
            switch (sortOrder)
            {
                case "name_desc":
                    answers = answers.OrderByDescending(q => q.Name);
                    break;
                case "CorrectChoice":
                    answers = answers.OrderBy(q => q.IsRightAnswer);
                    break;
                case "correctchoice_desc":
                    answers = answers.OrderByDescending(q => q.IsRightAnswer);
                    break;
                case "questionname_desc":
                    answers = answers.OrderBy(q => q.Question.Name);
                    break;
                case "QuestionName":
                    answers = answers.OrderByDescending(q => q.Question.Name);
                    break;
                default:
                    answers = answers.OrderBy(q => q.Name);
                    break;
            }
            var items = answers.ToPagedList(page ?? 1, 10);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_AnswerPartial", items);
            }
            return View(items);
        }

        // GET: Answers/Create
        public ActionResult Create()
        {
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name");
            return View();
        }

        // POST: Answers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,QuestionId,IsRightAnswer")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Answers.Add(answer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name", answer.QuestionId);
            return View(answer);
        }

        // POST: Answers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,QuestionId,IsRightAnswer")] Answer answer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(answer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewBag.QuestionId = new SelectList(db.Questions, "Id", "Name", answer.QuestionId);
            return View(answer);
        }

        // GET: Answers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Answer answer = await db.Answers.FindAsync(id);
            if (answer == null)
            {
                return HttpNotFound();
            }
            return View(answer);
        }

        // POST: Answers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Answer answer = await db.Answers.FindAsync(id);
            db.Answers.Remove(answer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult AutoComplete(string term)
        {
            var answers = db.Answers.Where(a => a.Name.ToUpper().Contains(term.ToUpper()) || a.Question.Name.ToUpper().Contains(term.ToUpper())).Select(a => a.Name);
            return Json(answers, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication5/WebApplication5/Controllers/CandidatesController.cs
using PagedList;
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using WebApplication5.Filters;
using WebApplication5.Helpers;
using WebApplication5.Models;
namespace WebApplication5.Controllers
{
    [AdminAuthorizeAttribute]
    public class CandidatesController : Controller
    {
        private OnlineAptitudeTestEntities db = new OnlineAptitudeTestEntities();

        // GET: Candidates
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.AddressSortParm = sortOrder == "Address" ? "address_desc" : "Address";
            ViewBag.GenderSortParm = sortOrder == "Gender" ? "gender_desc" : "Gender";
            ViewBag.BirthdaySortParm = sortOrder == "Birthday" ? "birthday_desc" : "Birthday";
            ViewBag.PassedSortParm = sortOrder == "Passed" ? "passed_desc" : "Passed";
            ViewBag.EmailSortParm = sortOrder == "Email" ? "email_desc" : "Email";
            ViewBag.DateTakenSortParm = sortOrder == "DateTaken" ? "datetaken_desc" : "DateTaken";
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;
            var candidates = from q in db.Candidates select q;
            if (!String.IsNullOrEmpty(searchString))
            {
                candidates = candidates.Where(c => c.Name.ToUpper().Contains(searchString.ToUpper()) || c.Email.ToUpper().Contains(searchString.ToUpper()) || c.HomeAddress.ToUpper().Contains(searchString.ToUpper()));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    candidates = candidates.OrderByDescending(q => q.Name);
                    break;
                case "Address":
                    candidates = candidates.OrderBy(q => q.HomeAddress);
                    break;
                case "address_desc":
                    candidates = candidates.OrderByDescending(q => q.HomeAddress);
                    break;
                case "Gender":
                    candidates = candidates.OrderBy(q => q.Gender);
                    break;
                case "gender_desc":
                    candidates = candidates.OrderByDescending(q => q.Gender);
                    break;
                case "Birthday":
                    candidates = candidates.OrderBy(c => c.Birthday);
                    break;
                case "birthday_desc":
                    candidates = candidates.OrderByDescending(c => c.Birthday);
                    break;
                case "Passed":
                    candidates = candidates.OrderBy(c => c.Passed);
                    break;
                case "passed_desc":
                    candidates = candidates.OrderByDescending(c => c.Passed);
                    break;
                case "Email":
                    candidates = candidates.OrderBy(c => c.Email);
                    break;
                case "email_desc":
                    candidates = candidates.OrderByDescending(c => c.Email);
                    break;
                case "DateTaken":
                    candidates = candidates.OrderBy(c => c.DateTaken);
                    break;
                case "datetaken_desc":
                    candidates = candidates.OrderByDescending(c => c.DateTaken);
                    break;
                default:
                    candidates = candidates.OrderBy(q => q.Name);
                    break;
            }
            var items = candidates.ToPagedList(page ?? 1, 10);
            if (Request.IsAjaxRequest())
            {
                return PartialView("_CandidatePartial", items);
            }
            return View(items);
        }

        // GET: Candidates/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = await db.Candidates.FindAsync(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // GET: Candidates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                candidate.Id = "CAN" + new Random().Next(1000000).ToString();
                candidate.Pass = RandomPassword.Generate(8, 12);
                db.Candidates.Add(candidate);
                await db.SaveChangesAsync();
                EmailSender.SendEmail(candidate.Email, "Your user name and password from Webster organization", "Your user name is :" + candidate.Id + "<br />" + "Your password is:" + candidate.Pass + "<br />" + "Use it to log in and take your aptitude test<br />Please take the test on " + candidate.DateAssigned.ToShortDateString());
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = await db.Candidates.FindAsync(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            Candidate candidate = await db.Candidates.FindAsync(id);
            db.Candidates.Remove(candidate);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        public JsonResult IsEmailAvailable(string Email)
        {
            var isAvail = (from candidate in db.Candidates where candidate.Email == Email select candidate).FirstOrDefault();
            if (isAvail == null)
            {
                return Json(true, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(false, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult FilterCandidatesByDate(DateTime? DateTaken)
        {
            ViewBag.Date = DateTaken.Value.ToShortDateString();
            var model = db.Candidates.Where(can => can.DateTaken.HasValue && DateTaken.HasValue && can.DateTaken.Value.Day == DateTaken.Value.Day && can.DateTaken.Value.Month == DateTaken.Value.Month && can.DateTaken.Value.Year == DateTaken.Value.Year);
            return View(model);
        }
    }
}

WebApplication5/WebApplication5/Views/Shared/_HomeLayoutPage.cshtml
@using WebApplication5.Models
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="The description of my page" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/normalize.css" rel="stylesheet" />
    <link href="~/Content/foundation.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.7.2.js"></script>
    @RenderSection("ClockCss", false)
</head>
<body>
    <div class="row">
        <div class="large-12 columns">

            <nav class="top-bar" data-topbar>
                <ul class="title-area">

                    <li class="name">
                        <h1>@Html.ActionLink("Webster Organization", "Index", "HomePage")</h1>
                    </li>
                    <li class="toggle-topbar menu-icon">
                        <a href="#"><span>menu</span></a>
                    </li>
                </ul>
                <section class="top-bar-section">
                    <ul class="right">
                        @if (Session["UserInfo"] == null)
                        {
                            <li>
                                @Html.ActionLink("Log in", "Login", "HomePage")
                            </li>
                        }
                        else
                        {
                            Candidate candidate = (Candidate)Session["UserInfo"];
                            <li><a href="#">Hello @candidate.Name!</a></li>
                        }
                    </ul>
                </section>
            </nav>
        </div>
    </div>
    @RenderBody()
    <footer class="row">
        <div class="large-12 columns">
            <hr>
            <div class="row">
                <div class="large-6 columns">
                    <p>© Copyright FPT Aptech Group 2.</p>
                </div>
                <div class="large-6 columns">
                    <ul class="inline-list right">
                        <li>
                            @Html.ActionLink("About Us", "AboutUs", "HomePage")
                        </li>
                        <li>
                            @Html.ActionLink("Contact Us", "ContactUs", "HomePage")
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/foundation.min.js"></script>
    @RenderSection("ClockJs", false)
    <script>
        $(document).foundation();
    </script>
    @RenderSection("ClockInit", false)
    @RenderSection("LeaveConfirmation", false)
</body>
</html>

WebApplication5/WebApplication5/Views/Shared/_LayoutPage.cshtml
@using WebApplication5.Models
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta name="description" content="The description of my page" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/normalize.css" rel="stylesheet" />
    <link href="~/Content/foundation.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.7.2.js"></script>
    @RenderSection("ResponsiveTable", false)
    @RenderSection("Paging", false)
    @RenderSection("AutoCompleteCss", false)
    @RenderSection("ChartCss", false)
</head>
<body>
    <nav class="top-bar" data-topbar>
        <ul class="title-area">
            <li class="name">
                <h1>
                    @Html.ActionLink("Admin Site", "Index", "Questions")
                </h1>
            </li>
            <li class="toggle-topbar menu-icon"><a href="#"><span>menu</span></a></li>
        </ul>
        <section class="top-bar-section">
            <ul class="left">
                <li class="divider"></li>
                <li>@Html.ActionLink("Question Bank", "Index", "Questions")</li>
                <li class="divider"></li>
                <li>@Html.ActionLink("Answer Bank", "Index", "Answers")</li>
                <li class="divider"></li>
                <li>@Html.ActionLink("Candidate Management", "Index", "Candidates")</li>
                <li class="divider"></li>
                <li>@Html.ActionLink("Statistics", "Index", "Statistics")</li>
            </ul>
            <ul class="right">
                <li>@Html.ActionLink("Sign Out", "SignOut", "Admin")</li>
            </ul>
        </section>
    </nav>
    <div class="row">
        <div class="large-12 columns">
            @RenderBody()
        </div>
    </div>
    <footer class="row">
        <div class="large-12 columns">
            <hr />
            <div class="row">
                <div class="large-6 columns">
                    <p>© Copyright FPT-Aptech. Group 2.</p>
                </div>
                <div class="large-6 columns">
                    <ul class="inline-list right">
                        <li>@Html.ActionLink("About Us", "AboutUs", "HomePage")</li>
                        <li>@Html.ActionLink("Contact Us", "ContactUs", "HomePage")</li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <script src="~/Scripts/jquery-2.1.1.min.js"></script>
    <script src="~/Scripts/foundation.min.js"></script>
    @RenderSection("ChartJs", false)
    <script>
        $(document).foundation();
    </script>
    @RenderSection("Chart", false)
    @RenderSection("ChartInit", false)
    @RenderSection("DataAbide", false)
    @RenderSection("Validation", false)
    @RenderSection("ResponsiveTableJs", false)
    @RenderSection("Ajax", false)
    @RenderSection("AutoCompleteJs", false)
    @RenderSection("AutoScript", false)
    @RenderSection("DatePicker", false)
    @RenderSection("HighChartJs", false)
</body>
</html>